const { readdir, createReadStream, writeFile } = require("fs-extra");
const { createInterface } = require("readline");
const { join, parse } = require("path");
const path = require("path");
const fs = require("fs/promises");

// This script is not part of faast.js, but rather a tool to rewrite some parts
// of the generated docs from api-generator and api-documenter so they work with
// the website generated by docusaurus.

function patchLine(line) {
  return line
    .replaceAll(/\]\(\.\/(doxygen2docusaurus[^)]*)\)/g, '](/doxygen2docusaurus-ts/docs/api/$1)')
    .replaceAll(/\.md\)/g, ')')
    .replaceAll(/\]\(([^)]*)\)/g, (match, content) => `](${content.replace(/\./g, '/')})`)
    .replaceAll(/_constructor_/g, '$constructor$')
}

async function main() {
    const inputFolderPath = 'api-extractor/markdown'
    const outputFolderPath = "website/docs/api";
    const mdFilesNames = await readdir(inputFolderPath);
    for (const mdFileName of mdFilesNames) {
        try {
            const { name: id, ext } = parse(mdFileName);
            if (ext !== ".md") {
                continue;
            }

            const mdInputFilePath = join(inputFolderPath, mdFileName);
            const inputStream = createReadStream(mdInputFilePath);

            const output = [];
            const lines = createInterface({
                input: inputStream,
                crlfDelay: Infinity
            });

            let title = "";
            lines.on("line", line => {
                let skip = false;
                if (!title) {
                    const titleLine = line.match(/## (.*)/);
                    if (titleLine) {
                        title = titleLine[1];
                    }
                }

                if (line !== '[Home](./index.md)') {
                  const homeLink = line.match(/\[Home\]\(.\/index\.md\) &gt; (.*)/);
                  if (homeLink) {
                      // Skip the breadcrumb for the toplevel index file.
                      if (id !== "doxygen2docusaurus") {
                          output.push(patchLine(homeLink[1]));
                      }
                      skip = true;
                  }
                } else {
                  skip = true;
                }
                // See issue #4. api-documenter expects \| to escape table
                // column delimiters, but docusaurus uses a markdown processor
                // that doesn't support this. Replace with an escape sequence
                // that renders |.
                if (line.startsWith("|")) {
                    line = line.replace(/\\\|/g, "&#124;");
                }
                line = patchLine(line)
                if (!skip) {
                    output.push(line);
                }
            });

            await new Promise(resolve => lines.once("close", resolve));
            inputStream.close();

            const slug = id === 'index' ? '/api' : `/api/${id.replace(/\./g, '/').replaceAll(/_constructor_/g, '$constructor$')}`;

            const header = [
              "---",
              `slug: ${slug}`,
              `title: ${title}`,
              `hide_title: true`,
              "---",
              "",
              "<div class=\"tsdocPage\">",
              "",
            ];

            const footer = [
              "",
              "</div>"
            ];

            const mdOutFilePath = id.replace(/\./g, '/').replaceAll(/_constructor_/g, '$constructor$') + ".md";
            console.log(`Writing ${mdOutFilePath}...`);

            const mdOutFolderPath = path.dirname(path.join(outputFolderPath,mdOutFilePath))
            await fs.mkdir(mdOutFolderPath, { recursive: true });

            const docFilePath = join(outputFolderPath, mdOutFilePath);
            await writeFile(docFilePath, header.concat(output).concat(footer).join("\n"));
        } catch (err) {
            console.error(`Could not process ${mdFileName}: ${err}`);
        }
    }
}

main();
